//! Static validation of a ViewDefinition's FHIRPath selectors against the FHIR
//! schema, plus analysis of the generated SQL through the analysis engine.
//!
//! This is the differentiating layer: the FHIRPath column/where/forEach
//! selectors are parsed with the real FHIRPath parser and walked against the
//! [`FhirSchemaProvider`] so that unknown fields and un-narrowed collections are
//! reported before any SQL runs.

use banshee_hir::{AnalysisOptions, BuiltinLintPack, SchemaProvider, analyze_query_with_options};
use octofhir_fhirpath::{ExpressionNode, parse_ast};
use octofhir_sof::{Column, SelectColumn, SqlGenerator, ViewDefinition};

use crate::finding::{Finding, Severity};
use crate::provider::{ElementKind, FhirSchemaProvider};

/// One navigation step extracted from a FHIRPath selector.
enum Step {
    /// A property navigation (`.name`).
    Field(String),
    /// A function that reduces a collection to a single item (`first()`, `[0]`).
    Collapse,
    /// `ofType(T)` — narrows a choice; deeper navigation is not resolved.
    OfType,
    /// Any other function. `where()` keeps the collection; everything else ends
    /// resolvable navigation.
    Func(String),
}

/// Lint a ViewDefinition: structural validation, selector validation against
/// the schema, plus generated-SQL analysis.
pub fn lint(view: &ViewDefinition, provider: &FhirSchemaProvider) -> Vec<Finding> {
    let mut findings = crate::structure::validate_structure(view);
    findings.extend(lint_view(view, provider));
    if let Ok(generated) = SqlGenerator::new().generate(view) {
        findings.extend(lint_sql(&generated.sql, provider));
    }
    findings
}

/// Validate the ViewDefinition's FHIRPath selectors against the schema.
pub fn lint_view(view: &ViewDefinition, provider: &FhirSchemaProvider) -> Vec<Finding> {
    let mut findings = Vec::new();
    let resource = view.resource.clone();
    walk_selects(&view.select, &resource, provider, &mut findings);
    for w in &view.where_ {
        check_selector(&w.path, &resource, false, provider, &mut findings);
    }
    findings
}

/// Analyse generated SQL through the engine with the FHIR schema provider and
/// the JSONB-aware builtin lint packs.
pub fn lint_sql(sql: &str, provider: &FhirSchemaProvider) -> Vec<Finding> {
    let parse = banshee_parser::parse(sql);
    // Only the JSONB pack: the SQL is generated by this crate, so stylistic
    // checks on it are not user-actionable; the JSONB checks catch field-shape
    // problems against the FHIR schema provider.
    let options = AnalysisOptions::new().with_builtin_lint_packs([BuiltinLintPack::Jsonb]);
    let analysis = analyze_query_with_options(&parse, provider as &dyn SchemaProvider, &options);

    analysis
        .diagnostics
        .into_iter()
        .map(|d| {
            let code = d
                .code
                .map(|c| format!("{c:?}"))
                .unwrap_or_else(|| "SQL".to_string());
            let help_url = d
                .code
                .map(|c| format!("https://octofhir.github.io/banshee/rules/{c:?}"));
            Finding {
                code,
                message: d.message,
                severity: match d.severity {
                    banshee_hir::Severity::Error => Severity::Error,
                    _ => Severity::Warning,
                },
                location: None,
                help_url,
            }
        })
        .collect()
}

fn walk_selects(
    selects: &[SelectColumn],
    resource: &str,
    provider: &FhirSchemaProvider,
    out: &mut Vec<Finding>,
) {
    for select in selects {
        if let Some(path) = &select.for_each {
            check_selector(path, resource, true, provider, out);
        }
        if let Some(path) = &select.for_each_or_null {
            check_selector(path, resource, true, provider, out);
        }
        if let Some(columns) = &select.column {
            for col in columns {
                check_column(col, resource, provider, out);
            }
        }
        walk_selects(&select.select, resource, provider, out);
        if let Some(union) = &select.union_all {
            walk_selects(union, resource, provider, out);
        }
    }
}

fn check_column(
    col: &Column,
    resource: &str,
    provider: &FhirSchemaProvider,
    out: &mut Vec<Finding>,
) {
    let collection = col.collection.unwrap_or(false);
    check_selector_named(
        &col.path, &col.name, resource, collection, true, provider, out,
    );
}

fn check_selector(
    path: &str,
    resource: &str,
    is_collection_context: bool,
    provider: &FhirSchemaProvider,
    out: &mut Vec<Finding>,
) {
    check_selector_named(
        path,
        path,
        resource,
        is_collection_context,
        false,
        provider,
        out,
    );
}

#[allow(clippy::too_many_arguments)]
fn check_selector_named(
    path: &str,
    location: &str,
    resource: &str,
    collection_ok: bool,
    is_column: bool,
    provider: &FhirSchemaProvider,
    out: &mut Vec<Finding>,
) {
    let Ok(ast) = parse_ast(path) else {
        return; // parse errors are surfaced elsewhere; don't double-report
    };
    let mut steps = Vec::new();
    if !linearize(&ast, &mut steps) {
        return; // not a plain navigation (operators, etc.) — skip conservatively
    }
    validate_steps(
        &steps,
        location,
        resource,
        collection_ok,
        is_column,
        provider,
        out,
    );
}

#[allow(clippy::too_many_arguments)]
fn validate_steps(
    steps: &[Step],
    location: &str,
    resource: &str,
    collection_ok: bool,
    is_column: bool,
    provider: &FhirSchemaProvider,
    out: &mut Vec<Finding>,
) {
    let table = resource.to_lowercase();
    let mut path: Vec<String> = Vec::new();
    let mut pending_array = false;
    let mut resolvable = true;
    let mut fh04_emitted = false;

    for (i, step) in steps.iter().enumerate() {
        match step {
            Step::Field(f) => {
                if path.is_empty() && f == resource {
                    continue; // leading resource type
                }
                if !resolvable {
                    continue;
                }
                let parent: Vec<&str> = path.iter().map(String::as_str).collect();
                match provider.lookup_jsonb_fields(None, &table, "resource", &parent) {
                    Some(fields) => {
                        if !fields.iter().any(|x| x == f) {
                            out.push(unknown_field(f, &fields, location));
                            resolvable = false;
                            continue;
                        }
                        if pending_array && !fh04_emitted {
                            out.push(array_navigation(location));
                            fh04_emitted = true;
                        }
                        path.push(f.clone());
                        let refs: Vec<&str> = path.iter().map(String::as_str).collect();
                        pending_array = provider
                            .jsonb_field_is_array(None, &table, "resource", &refs)
                            == Some(true);
                        if provider.is_choice_at(resource, &refs)
                            && !matches!(steps.get(i + 1), Some(Step::OfType))
                        {
                            out.push(choice_not_narrowed(f, location));
                            resolvable = false;
                        }
                    }
                    None => resolvable = false,
                }
            }
            Step::Collapse => pending_array = false,
            Step::OfType => resolvable = false,
            Step::Func(name) if name == "where" => {}
            Step::Func(_) => resolvable = false,
        }
    }

    if resolvable && pending_array && !collection_ok && !fh04_emitted {
        out.push(array_terminal(location));
    }

    // Type-shape checks for scalar column selectors: the spec expects a column
    // to yield a primitive value. A non-array path that lands on a Reference or
    // any other complex element is flagged (FH05/FH03). Array terminals are
    // already covered by FH04; collection columns opt into structured output.
    if is_column && resolvable && !collection_ok && !pending_array && !path.is_empty() {
        let refs: Vec<&str> = path.iter().map(String::as_str).collect();
        match provider.element_kind_at(resource, &refs) {
            Some(ElementKind::Reference) => out.push(reference_not_resolved(location)),
            Some(ElementKind::Complex) => out.push(complex_into_scalar(location)),
            _ => {}
        }
    }
}

fn unknown_field(field: &str, valid: &[String], location: &str) -> Finding {
    let mut msg = format!("unknown FHIR element `{field}`");
    let suggestions = banshee_hir::suggest_similar(field, valid, 1);
    if let Some(s) = suggestions.first() {
        msg.push_str(&format!(" — did you mean `{s}`?"));
    }
    Finding::fhir("FH01", Severity::Error, msg).at(location)
}

fn choice_not_narrowed(field: &str, location: &str) -> Finding {
    Finding::fhir(
        "FH02",
        Severity::Warning,
        format!(
            "selects choice element `{field}` without narrowing; add \
             ofType(<Type>) to pick a concrete type before extracting a value"
        ),
    )
    .at(location)
}

fn reference_not_resolved(location: &str) -> Finding {
    Finding::fhir(
        "FH05",
        Severity::Warning,
        "selects a Reference element directly; use getReferenceKey() to extract \
         a stable key, or navigate to a primitive such as .reference",
    )
    .at(location)
}

fn complex_into_scalar(location: &str) -> Finding {
    Finding::fhir(
        "FH03",
        Severity::Warning,
        "selects a complex element into a scalar column; navigate to a primitive \
         leaf, or mark the column collection to emit structured JSON",
    )
    .at(location)
}

fn array_navigation(location: &str) -> Finding {
    Finding::fhir(
        "FH04",
        Severity::Warning,
        "navigates into an array element without narrowing; the result is a \
         collection (use first()/where()/an index, or mark the column collection)",
    )
    .at(location)
}

fn array_terminal(location: &str) -> Finding {
    Finding::fhir(
        "FH04",
        Severity::Warning,
        "selects an array-valued element into a scalar column; narrow it \
         (first()/where()/index) or mark the column collection",
    )
    .at(location)
}

/// Flatten a navigation expression into ordered steps. Returns `false` for
/// expressions that are not plain navigation (binary ops, unions, literals).
fn linearize(expr: &ExpressionNode, out: &mut Vec<Step>) -> bool {
    match expr {
        ExpressionNode::Identifier(n) => {
            out.push(Step::Field(n.name.clone()));
            true
        }
        ExpressionNode::PropertyAccess(p) => {
            if !linearize(&p.object, out) {
                return false;
            }
            out.push(Step::Field(p.property.clone()));
            true
        }
        ExpressionNode::MethodCall(m) => {
            if !linearize(&m.object, out) {
                return false;
            }
            push_func(&m.method, out);
            true
        }
        ExpressionNode::FunctionCall(f) => {
            push_func(&f.name, out);
            true
        }
        ExpressionNode::IndexAccess(i) => {
            if !linearize(&i.object, out) {
                return false;
            }
            out.push(Step::Collapse);
            true
        }
        ExpressionNode::Parenthesized(e) => linearize(e, out),
        _ => false,
    }
}

fn push_func(name: &str, out: &mut Vec<Step>) {
    match name {
        "first" | "last" | "single" | "tail" => out.push(Step::Collapse),
        "ofType" => out.push(Step::OfType),
        other => out.push(Step::Func(other.to_string())),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use octofhir_fhirschema::FhirSchema;
    use serde_json::json;

    fn provider() -> FhirSchemaProvider {
        let patient: FhirSchema = serde_json::from_value(json!({
            "url": "u", "name": "Patient", "type": "Patient",
            "kind": "resource", "class": "resource",
            "elements": {
                "id": { "type": "id" },
                "gender": { "type": "code" },
                "name": { "type": "HumanName", "array": true },
                "managingOrganization": { "type": "Reference" },
                "generalPractitioner": { "type": "Reference", "array": true }
            }
        }))
        .unwrap();
        let hn: FhirSchema = serde_json::from_value(json!({
            "url": "u", "name": "HumanName", "type": "HumanName",
            "kind": "complex-type", "class": "complex-type",
            "elements": {
                "family": { "type": "string" },
                "given": { "type": "string", "array": true }
            }
        }))
        .unwrap();
        FhirSchemaProvider::with_schemas([patient, hn])
    }

    fn view(path: &str, collection: bool) -> ViewDefinition {
        let v = json!({
            "resource": "Patient",
            "select": [{ "column": [{ "name": "c", "path": path, "collection": collection }] }]
        });
        ViewDefinition::from_json(&v).unwrap()
    }

    fn codes(fs: &[Finding]) -> Vec<&str> {
        fs.iter().map(|f| f.code.as_str()).collect()
    }

    #[test]
    fn known_scalar_is_clean() {
        let f = lint_view(&view("gender", false), &provider());
        assert!(f.is_empty(), "{f:?}");
    }

    #[test]
    fn unknown_field_reports_fh01() {
        let f = lint_view(&view("gendr", false), &provider());
        assert_eq!(codes(&f), vec!["FH01"]);
        assert!(f[0].message.contains("did you mean `gender`"));
    }

    #[test]
    fn unknown_nested_field_reports_fh01() {
        let f = lint_view(&view("name.familly", false), &provider());
        assert_eq!(codes(&f), vec!["FH01"]);
        assert!(f[0].message.contains("family"));
    }

    #[test]
    fn array_into_scalar_reports_fh04() {
        // name is an array; name.family across all names is a collection
        let f = lint_view(&view("name.family", false), &provider());
        assert_eq!(codes(&f), vec!["FH04"]);
    }

    #[test]
    fn narrowed_array_is_clean() {
        let f = lint_view(&view("name.first().family", false), &provider());
        assert!(f.is_empty(), "{f:?}");
    }

    #[test]
    fn array_terminal_into_collection_is_clean() {
        let f = lint_view(&view("name", true), &provider());
        assert!(f.is_empty(), "{f:?}");
    }

    #[test]
    fn array_terminal_into_scalar_reports_fh04() {
        let f = lint_view(&view("name", false), &provider());
        assert_eq!(codes(&f), vec!["FH04"]);
    }

    #[test]
    fn reference_into_scalar_reports_fh05() {
        let f = lint_view(&view("managingOrganization", false), &provider());
        assert_eq!(codes(&f), vec!["FH05"]);
    }

    #[test]
    fn reference_key_is_clean() {
        let f = lint_view(
            &view("managingOrganization.getReferenceKey()", false),
            &provider(),
        );
        assert!(f.is_empty(), "{f:?}");
    }

    #[test]
    fn reference_navigated_to_primitive_is_clean() {
        // .reference is a primitive string leaf on Reference; not modelled here,
        // so navigation past Reference is unresolved and must not false-positive.
        let f = lint_view(&view("gender", false), &provider());
        assert!(f.is_empty(), "{f:?}");
    }

    #[test]
    fn complex_into_scalar_reports_fh03() {
        // name.first() lands on a HumanName (complex) in a scalar column.
        let f = lint_view(&view("name.first()", false), &provider());
        assert_eq!(codes(&f), vec!["FH03"]);
    }

    #[test]
    fn complex_into_collection_is_clean() {
        let f = lint_view(&view("name.first()", true), &provider());
        assert!(f.is_empty(), "{f:?}");
    }

    fn obs_provider() -> FhirSchemaProvider {
        let obs: FhirSchema = serde_json::from_value(json!({
            "url": "u", "name": "Observation", "type": "Observation",
            "kind": "resource", "class": "resource",
            "elements": {
                "id": { "type": "id" },
                "status": { "type": "code" },
                "value": { "choices": ["valueQuantity", "valueString"] },
                "valueQuantity": { "type": "Quantity", "choiceOf": "value" },
                "valueString": { "type": "string", "choiceOf": "value" }
            }
        }))
        .unwrap();
        FhirSchemaProvider::with_schemas([obs])
    }

    fn obs_view(path: &str) -> ViewDefinition {
        ViewDefinition::from_json(&json!({
            "resource": "Observation",
            "select": [{ "column": [{ "name": "c", "path": path }] }]
        }))
        .unwrap()
    }

    #[test]
    fn choice_terminal_reports_fh02() {
        let f = lint_view(&obs_view("value"), &obs_provider());
        assert_eq!(codes(&f), vec!["FH02"]);
    }

    #[test]
    fn choice_navigated_reports_fh02() {
        let f = lint_view(&obs_view("value.unit"), &obs_provider());
        assert_eq!(codes(&f), vec!["FH02"]);
    }

    #[test]
    fn narrowed_choice_is_clean() {
        let f = lint_view(&obs_view("value.ofType(Quantity)"), &obs_provider());
        assert!(f.is_empty(), "{f:?}");
    }

    #[test]
    fn concrete_choice_field_is_clean() {
        let f = lint_view(&obs_view("valueString"), &obs_provider());
        assert!(f.is_empty(), "{f:?}");
    }
}
